use egui_term::ColorPalette;

pub fn get_theme(name: &str) -> ColorPalette {
    match name {
        "solarized" => solarized(),
        "gruvbox" => gruvbox(),
        "dracula" => dracula(),
        _ => one_dark(),
    }
}

pub fn one_dark() -> ColorPalette {
    ColorPalette {
        foreground: String::from("#abb2bf"),
        background: String::from("#282c34"),
        black: String::from("#282c34"),
        red: String::from("#e06c75"),
        green: String::from("#98c379"),
        yellow: String::from("#e5c07b"),
        blue: String::from("#61afef"),
        magenta: String::from("#c678dd"),
        cyan: String::from("#56b6c2"),
        white: String::from("#abb2bf"),
        bright_black: String::from("#5c6370"),
        bright_red: String::from("#e06c75"),
        bright_green: String::from("#98c379"),
        bright_yellow: String::from("#e5c07b"),
        bright_blue: String::from("#61afef"),
        bright_magenta: String::from("#c678dd"),
        bright_cyan: String::from("#56b6c2"),
        bright_white: String::from("#ffffff"),
        bright_foreground: None,
        dim_foreground: String::from("#6b7280"),
        dim_black: String::from("#1c2026"),
        dim_red: String::from("#9c4f56"),
        dim_green: String::from("#6c8f57"),
        dim_yellow: String::from("#a6895a"),
        dim_blue: String::from("#477cab"),
        dim_magenta: String::from("#8d559d"),
        dim_cyan: String::from("#3d828a"),
        dim_white: String::from("#757b85"),
    }
}

pub fn solarized() -> ColorPalette {
    ColorPalette {
        foreground: String::from("#839496"),
        background: String::from("#002b36"),
        black: String::from("#073642"),
        red: String::from("#dc322f"),
        green: String::from("#859900"),
        yellow: String::from("#b58900"),
        blue: String::from("#268bd2"),
        magenta: String::from("#d33682"),
        cyan: String::from("#2aa198"),
        white: String::from("#eee8d5"),
        bright_black: String::from("#586e75"),
        bright_red: String::from("#cb4b16"),
        bright_green: String::from("#859900"),
        bright_yellow: String::from("#b58900"),
        bright_blue: String::from("#268bd2"),
        bright_magenta: String::from("#d33682"),
        bright_cyan: String::from("#2aa198"),
        bright_white: String::from("#fdf6e3"),
        bright_foreground: None,
        dim_foreground: String::from("#657b83"),
        dim_black: String::from("#053440"),
        dim_red: String::from("#a22824"),
        dim_green: String::from("#667600"),
        dim_yellow: String::from("#886800"),
        dim_blue: String::from("#1d6a9c"),
        dim_magenta: String::from("#a02963"),
        dim_cyan: String::from("#207a72"),
        dim_white: String::from("#b6b3a6"),
    }
}

pub fn gruvbox() -> ColorPalette {
    ColorPalette {
        foreground: String::from("#ebdbb2"),
        background: String::from("#282828"),
        black: String::from("#282828"),
        red: String::from("#cc241d"),
        green: String::from("#98971a"),
        yellow: String::from("#d79921"),
        blue: String::from("#458588"),
        magenta: String::from("#b16286"),
        cyan: String::from("#689d6a"),
        white: String::from("#a89984"),
        bright_black: String::from("#928374"),
        bright_red: String::from("#fb4934"),
        bright_green: String::from("#b8bb26"),
        bright_yellow: String::from("#fabd2f"),
        bright_blue: String::from("#83a598"),
        bright_magenta: String::from("#d3869b"),
        bright_cyan: String::from("#8ec07c"),
        bright_white: String::from("#ebdbb2"),
        bright_foreground: None,
        dim_foreground: String::from("#a89984"),
        dim_black: String::from("#1d2021"),
        dim_red: String::from("#9d1a15"),
        dim_green: String::from("#7a7014"),
        dim_yellow: String::from("#a77619"),
        dim_blue: String::from("#36656a"),
        dim_magenta: String::from("#894a69"),
        dim_cyan: String::from("#4f7452"),
        dim_white: String::from("#837768"),
    }
}

pub fn dracula() -> ColorPalette {
    ColorPalette {
        foreground: String::from("#f8f8f2"),
        background: String::from("#282a36"),
        black: String::from("#21222c"),
        red: String::from("#ff5555"),
        green: String::from("#50fa7b"),
        yellow: String::from("#f1fa8c"),
        blue: String::from("#bd93f9"),
        magenta: String::from("#ff79c6"),
        cyan: String::from("#8be9fd"),
        white: String::from("#f8f8f2"),
        bright_black: String::from("#6272a4"),
        bright_red: String::from("#ff6e6e"),
        bright_green: String::from("#69ff94"),
        bright_yellow: String::from("#ffffa5"),
        bright_blue: String::from("#d6acff"),
        bright_magenta: String::from("#ff92df"),
        bright_cyan: String::from("#a4ffff"),
        bright_white: String::from("#ffffff"),
        bright_foreground: None,
        dim_foreground: String::from("#9a9a9a"),
        dim_black: String::from("#1a1c24"),
        dim_red: String::from("#bf4040"),
        dim_green: String::from("#3cbb5d"),
        dim_yellow: String::from("#b4bc69"),
        dim_blue: String::from("#8d6ebb"),
        dim_magenta: String::from("#bf5a95"),
        dim_cyan: String::from("#68aebe"),
        dim_white: String::from("#bbbbbb"),
    }
}
